name: Continuous integration

on:
  push:
    paths-ignore:
      - "CHANGELOG.adoc"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - "doc/**"
    branches:
      - "**"
    tags:
      - "*"
  pull_request:
    paths-ignore:
      - "CHANGELOG.adoc"
      - ".github/PULL_REQUEST_TEMPLATE.md"
      - "doc/**"
  workflow_dispatch:

env:
  GITHUB_EVENT_NAME: ${{ github.event_name }}
  GITHUB_EVENT_PR_HEAD_REPO_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
  GITHUB_EVENT_PR_BASE_REPO_FULL_NAME: ${{ github.event.pull_request.base.repo.full_name }}
  GITHUB_EVENT_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: ${{ env.GITHUB_EVENT_NAME != 'pull_request' }}
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: ${{ env.GITHUB_EVENT_NAME == 'pull_request' }}
        with:
          ref: ${{ env.GITHUB_EVENT_PR_HEAD_SHA }}
          persist-credentials: false

      - name: Set up QEMU to build the Docker image for additional platforms
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx to use cache feature
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Verify the application source with Docker
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: docker compose -f docker-compose.yml -f .github/workflows/compose.ci.yml run --build --rm verify

      - name: Archive the code coverage results
        run: tar -cf coverage.tar -C build-artifacts backend/releng/syson-test-coverage/target/site/jacoco-aggregate

      - name: Store code coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: jacoco
          path: coverage.tar
          retention-days: 5

      - name: Publish the backend
        if: startsWith(env.GITHUB_REF, 'refs/tags/v')
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          target: backend-publish
          build-args: |
            USERNAME=${{ github.actor }}
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          no-cache-filters: backend-publish
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Publish the frontend packages
        if: startsWith(env.GITHUB_REF, 'refs/tags/v')
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          target: frontend-publish
          secrets: |
            github_token=${{ secrets.GITHUB_TOKEN }}
          no-cache-filters: frontend-publish
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: eclipsesyson/syson

      - name: Package the verified JAR as a Docker image
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          BUILD_TARGET: prebuilt
          IMAGE_TAG: eclipsesyson/syson:${{ steps.meta.outputs.version }}
          IMAGE_TAGS: ${{ steps.meta.outputs.tags }}
          IMAGE_CREATED: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          IMAGE_DESCRIPTION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.description'] }}
          IMAGE_LICENSES: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.licenses'] }}
          IMAGE_REVISION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          IMAGE_SOURCE: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.source'] }}
          IMAGE_TITLE: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.title'] }}
          IMAGE_URL: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.url'] }}
          IMAGE_VERSION: ${{ steps.meta.outputs.version }}
        run: |
          docker compose build app
          while IFS= read -r tag; do
            docker tag "eclipsesyson/syson:${{ steps.meta.outputs.version }}" "$tag"
          done <<< "$IMAGE_TAGS"

      - name: Set up Node SDK for integration tests
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.20"
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check the Playwright integration test code
        run: |
          npm ci
          npm run eslint
        working-directory: integration-tests-playwright

      - name: Install Playwright Browsers
        if: startsWith(env.GITHUB_REF, 'refs/tags/v') == false && env.GITHUB_REF != 'refs/heads/main' && env.GITHUB_REF != 'refs/heads/cooldown'
        run: npx playwright install --with-deps
        working-directory: integration-tests-playwright

      - name: Run Playwright tests against the application
        if: startsWith(env.GITHUB_REF, 'refs/tags/v') == false && env.GITHUB_REF != 'refs/heads/main' && env.GITHUB_REF != 'refs/heads/cooldown'
        run: |
          docker compose -f ../docker-compose.yml -f ../.github/workflows/compose.ci.yml up -d --no-build
          docker compose -f ../docker-compose.yml -f ../.github/workflows/compose.ci.yml ps
          npx wait-on -t 180000 http://localhost:8080
          npx playwright test
        working-directory: integration-tests-playwright
        env:
          IMAGE_TAG: eclipsesyson/syson:${{ steps.meta.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store Playwright report
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: playwright-report
          path: integration-tests-playwright/playwright-report/
          retention-days: 5

      - name: Check the Cypress integration test code
        run: |
          npm ci
          npm run eslint
        working-directory: integration-tests-cypress

      - name: Run Cypress end to end tests against the application
        if: startsWith(env.GITHUB_REF, 'refs/tags/v') == false && env.GITHUB_REF != 'refs/heads/main' && env.GITHUB_REF != 'refs/heads/cooldown'
        uses: cypress-io/github-action@09090944bd8aaa2a517cefb6e38bf1aae336b42b # v7.4.3
        with:
          build: docker compose -f ../docker-compose.yml -f ../.github/workflows/compose.ci.yml up -d --no-build
          start: docker compose -f ../docker-compose.yml -f ../.github/workflows/compose.ci.yml ps
          wait-on: "http://localhost:8080"
          wait-on-timeout: 180
          working-directory: integration-tests-cypress
          record: false
        env:
          IMAGE_TAG: eclipsesyson/syson:${{ steps.meta.outputs.version }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store Cypress screenshots
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: cypress-screenshots
          path: integration-tests-cypress/target/screenshots/**/*.png
          retention-days: 5

      - name: Log in to Docker Hub
        if: env.GITHUB_EVENT_NAME == 'push' && (env.GITHUB_REF == 'refs/heads/main' || startsWith(env.GITHUB_REF, 'refs/tags/v'))
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ env.DOCKER_HUB_TOKEN }}
        env:
          DOCKER_HUB_USER: ${{ secrets.ORG_DOCKER_HUB_USER }}
          DOCKER_HUB_TOKEN: ${{ secrets.ORG_DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        if: env.GITHUB_EVENT_NAME == 'push' && (env.GITHUB_REF == 'refs/heads/main' || startsWith(env.GITHUB_REF, 'refs/tags/v'))
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          target: prebuilt
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
